services:
    nekstati.antibot42.xjBma:
        class: nekstati\antibot42\xjBma
        arguments:
            - '@nekstati.antibot42.WmAC_'
            - '@nekstati.antibot42.AcCvK'
        tags:
            - { name: event.listener }

    nekstati.antibot42.AcCvK:
        class: nekstati\antibot42\AcCvK
        arguments:
            - '@auth'
            - '@config'
            - '@request'
            - '@template'
            - '@user'
            - '@config_text'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@nekstati.antibot42.pCE9r'
        tags:
            - { name: event.listener }

    nekstati.antibot42.WmAC_:
        class: nekstati\antibot42\WmAC_
        arguments:
            - '@config'
            - '@request'
            - '@template'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'

    nekstati.antibot42.pCE9r:
        class: nekstati\antibot42\pCE9r
        arguments:
            - '@config'
            - '@controller.helper'
            - '@dbal.conn'
            - '@template'
            - '@user'
            - '%core.root_path%'
        calls:
            - [pkL3p, ['@?router']] # Optional service that doesn’t exist in phpBB 3.1
