services:
    nekstati.antibot42.m_Qev:
        class: nekstati\antibot42\m_Qev
        arguments:
            - '@nekstati.antibot42.QT0JZ'
            - '@nekstati.antibot42.DhEYv'
        tags:
            - { name: event.listener }

    nekstati.antibot42.DhEYv:
        class: nekstati\antibot42\DhEYv
        arguments:
            - '@auth'
            - '@config'
            - '@request'
            - '@template'
            - '@user'
            - '@config_text'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@nekstati.antibot42.ft07_'
        tags:
            - { name: event.listener }

    nekstati.antibot42.QT0JZ:
        class: nekstati\antibot42\QT0JZ
        arguments:
            - '@config'
            - '@request'
            - '@template'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'

    nekstati.antibot42.ft07_:
        class: nekstati\antibot42\ft07_
        arguments:
            - '@config'
            - '@controller.helper'
            - '@dbal.conn'
            - '@template'
            - '@user'
            - '%core.root_path%'
        calls:
            - [NNefg, ['@?router']] # Optional service that doesn’t exist in phpBB 3.1
